---
bloxroute:
  hosts:
    bloxroute-1:
      ansible_host: 34.207.194.86 
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/bloXroute.pem"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"